// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4xyys1pEy-ApVyFdwOkMBhAOOlACTRLk',
    appId: '1:493998980701:web:0deea892739209835a97b4',
    messagingSenderId: '493998980701',
    projectId: 'book-7a41c',
    authDomain: 'book-7a41c.firebaseapp.com',
    storageBucket: 'book-7a41c.appspot.com',
    measurementId: 'G-1CSWE45S4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfCo2fQQ5pAg12QD7-UbIrpplMZ12mu3k',
    appId: '1:493998980701:android:c73dc307fcaaa93c5a97b4',
    messagingSenderId: '493998980701',
    projectId: 'book-7a41c',
    storageBucket: 'book-7a41c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo9ws0KDgQCzAikzi7z434lOvPPJTc5nw',
    appId: '1:493998980701:ios:e48793b5603368b05a97b4',
    messagingSenderId: '493998980701',
    projectId: 'book-7a41c',
    storageBucket: 'book-7a41c.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo9ws0KDgQCzAikzi7z434lOvPPJTc5nw',
    appId: '1:493998980701:ios:b3278a0a587b17775a97b4',
    messagingSenderId: '493998980701',
    projectId: 'book-7a41c',
    storageBucket: 'book-7a41c.appspot.com',
    iosBundleId: 'com.example.book.RunnerTests',
  );
}
